### ISSUE TITLE
Question - Why cookie not works ?

### ISSUE THREAD

**Issue by kossa** [codezero-be/cookie#2]
Hi,

I'm using Laravel 5.2, I downloaded your package, I tried this code in my controller, but I get null each time :

```
$cookie = \App::make('CodeZero\Cookie\Cookie');
$cookie->forever('cookieName', 'cookieValue');
dd( $cookie->get('cookieName'));
```

Thanks

**Comment by ivanvermeyen** [comment]
Hi, 

I encountered this same issue in the past. But I think this is expected behavior... (correct me if I'm wrong)

Laravel sends cookies along with the response. If you `dd()` there is no real response returned, so the cookie is lost. I tried this:

```
    $cookie = \App::make('CodeZero\Cookie\Cookie');
    $cookie->forever('cookieName', 'cookieValue');
    var_dump($cookie->get('cookieName')); // don't die and dump
    return view('home');
```

And then the cookie is set. But the expected value will only be dumped after you reload the page.
Also make sure your route has the `web` middleware.

Let me now if this works for you :)

**Comment by kossa** [comment]
You're right, just one thing when you execute the script for the first time you get `NULL` from the var_dump, because the cookie not exists yet, after refreshing the get the value the best way to use is :

in a Controller : 

```
$cookie = \App::make('CodeZero\Cookie\Cookie');
$cookie->forever('cookieName', 'cookieValue');
```

In View (or other controller) :

```
{{ $cookie->get('cookieName') }}
```

Thank you for dd, you saved my day ;)

**Comment by ivanvermeyen** [comment]
np, glad I could help :)
